# fly.toml app configuration file generated for test-image-convertor on 2024-01-24T12:39:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "image-convertor"
primary_region = "ord"

[build]

[env]
  ENCODING_QUALITY = "90"
  ENCODING_SPEED = "10"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "requests"
    hard_limit = 8
    soft_limit = 3

[[vm]]
  cpu_kind = "shared"
  cpus = 4
  memory_mb = 4096
